name: Build RPM
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y podman buildah

    - name: Build RPM
      run: |
        sudo bash build-in-container.sh

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.rpm
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        body: "latest built nginx binary"
